fn main() {
    println!("Chapter 9 Error Handling");

    section9_1();
}

fn section9_1(){
    println!("Section 9.1 Unrecoverable Errors With 'panic!'");
}
